#ifndef TEST_SCOPE_H
#define TEST_SCOPE_H

DECLARE_TEST_SUITE_START(Scope);
  DECLARE_SETUP_SUITE;
  DECLARE_TEARDOWN_SUITE;
  DECLARE_SETUP_TEST;
  DECLARE_TEARDOWN_TEST;

  DECLARE_TEST_CASE(Test1);
  DECLARE_TEST_CASE(Test2);
DECLARE_TEST_SUITE_END;

#endif // TEST_SCOPE_H
