#ifndef TEST_SCOPE_H
#define TEST_SCOPE_H

DECLARE_TEST_SUITE_START(Scope);
  DECLARE_TEST_SETUP;
  DECLARE_TEST_TEARDOWN;
  DECLARE_TEST_CASE(GlobalScope);
  DECLARE_TEST_CASE(ParentScope);
  DECLARE_TEST_CASE(ChildScopes);
  DECLARE_TEST_CASE(NameSpace);
  DECLARE_TEST_CASE(Class);
DECLARE_TEST_SUITE_END;

#endif // TEST_SCOPE_H
